### ISSUE TITLE
LJM repo/package

### ISSUE THREAD

**Issue by kaidokert** [labjack/labjack-ljm-python#1]
Is it possible for the labjack team to create an official repo here for the LJM library as well ? https://labjack.com/support/software/examples/ljm/python

Also publish to pypi. Would make it far easier to manage as dependency

**Comment by rolsen** [comment]
@peircej, yes, LJM is for T-series only (T4, T7). Also, yes, you are correct that the LabJackM library files (.dylib/.so/.dll) aren't packaged. We're thinking about ways to programmatically install that, though.

@mnaberez, good point. The transfer seems to have worked.

**Comment by rolsen** [comment]
To be explicit, the current place to get the LJM library files is here:

https://labjack.com/support/software/installers/ljm
