### ISSUE TITLE
M1 mac support

### ISSUE THREAD

**Issue by jmarkow** [labjack/labjack-ljm-python#11]
Looks like the compiled libraries are not build against arm64. After pip installing I get the following error when importing ljm

```
<class 'labjack.ljm.ljm.LJMError'>: Cannot load the LJM library /usr/local/lib/libLabJackM.dylib. dlopen(libLabJackM.dylib, 0x0006): tried: '/Users/jeffreymarkowitz/miniconda3/envs/labjack-test/lib/python3.10/lib-dynload/../../libLabJackM.dylib' (no such file), '/Users/jeffreymarkowitz/miniconda3/envs/labjack-test/bin/../lib/libLabJackM.dylib' (no such file), 'libLabJackM.dylib' (no such file), '/usr/local/lib/libLabJackM.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))), '/usr/lib/libLabJackM.dylib' (no such file), '/Users/jeffreymarkowitz/libLabJackM.dylib' (no such file)
```

Are there plans to update for supporting M1 macs?

**Comment by jmarkow** [comment]
For context I noticed this forum post from back in 2021...

https://old3.labjack.com/forums/t7/liblabjackmdylib-problem-m1-mac

Any progress since then?

**Comment by sjarman28** [comment]
We currently do not support M1 Mac devices natively with LJM. We hope to have this support available in the next month or two.

**Comment by Prelly95** [comment]
Hi,
Has there been any progress on this?
Thanks.

**Comment by sjarman28** [comment]
Sorry for the delayed response. We now have a beta LJM installer for ARM based macOS devices:
https://labjack.com/pages/support?doc=/software-driver/installer-downloads/ljm-software-installers-t4-t7-digit/#section-header-two-41im2
