### ISSUE TITLE
CORE_TIMER read via streaming rolls over at 2^16

### ISSUE THREAD

**Issue by jmarkow** [labjack/labjack-ljm-python#13]
First, thanks so much for this library, developing for the Labjack is mostly a breeze!

We're running a program where we read in AIN0, AIN1 and FIO_STATE while using eReadStream. At the same time we're sending out TTL pulses via periodicStreamOut. To collect timestamps for our data reads we're also collecting CORE_TIMER – analog inputs are collected first, then FIO_STATE, then CORE_TIMER in the scan list. Even though the modbus map lists CORE_TIMER as a uint32, the returned values roll over at 2^16 rather than 2^32 as expected. Not sure if there's something in our configuration that would result in this happening.

**Comment by sjarman28** [comment]
This is expected behavior, stream only works with 16-bit data. See the following section of documentation about working with 32-bit registers:
https://labjack.com/pages/support?doc=/datasheets/t-series-datasheet/32-stream-mode-t-series-datasheet/#section-header-two-dqarj

**Comment by jmarkow** [comment]
Thanks again for the quick response, works as expected now.
