### ISSUE TITLE
Reading same DIO number for ASYNCH communication

### ISSUE THREAD

**Issue by nzmgng** [labjack/labjack-ljm-python#21]
For the T4 device,  setting the values for DIO 4 and 5 just like below. It ignores the first writeName function and overwrite its value on the second value also. The result will be `5, 5` instead of `4, 5`

```
        ljm.eWriteName(handle, "ASYNCH_TX_DIONUM", 4)  # TX pin number = 4 (FIO4)
        ljm.eWriteName(handle, "ASYNCH_RX_DIONUM", 5)  # RX pin number = 5 (FIO5)
        print(f"rx {int(ljm.eReadName(handle, 'ASYNCH_RX_DIONUM'))} \n")
        print(f"tx {int(ljm.eReadName(handle, 'ASYNCH_TX_DIONUM'))} \n")
```

**Comment by jdbrant3** [comment]
I am not able to replicate this behavior, could you provide the code for all of your LJM calls?

The sequence of LJM calls to configure async communication on the T4 is as follows from our asynch.py example:
`
handle = ljm.openS("T4", "ANY", "ANY")  # T4 device, Any connection, Any identifier
# Configure the asynch feature
ljm.eWriteName(handle, "ASYNCH_ENABLE", 0)

# Configure FIO4, FIO5, and FIO6 as digital I/O.
ljm.eWriteName(handle, "DIO_INHIBIT", 0xFFF8F)
ljm.eWriteName(handle, "DIO_ANALOG_ENABLE", 0x00000)

# For the T4, using FIO4 and FIO5 for RX and TX pins. FIO0 to FIO3 are
# reserved for analog inputs, and digital lines are required.
ljm.eWriteName(handle, "ASYNCH_RX_DIONUM", 4)  # RX pin number = 4 (FIO4)
ljm.eWriteName(handle, "ASYNCH_TX_DIONUM", 5)  # TX pin number = 5 (FIO5)

# Print out the configured RX and TX dio nums
print(f"rx {int(ljm.eReadName(handle, 'ASYNCH_RX_DIONUM'))} \n")
print(f"tx {int(ljm.eReadName(handle, 'ASYNCH_TX_DIONUM'))} \n")

`

**Comment by nzmgng** [comment]
This is a known issue for T4 cannot read the TX. you can find the detailed explanation in the following link https://support.labjack.com/docs/t4-firmware.
