### ISSUE TITLE
Some "Relevant Documentation" links are broken

### ISSUE THREAD

**Issue by tyjlin** [labjack/labjack-ljm-python#8]
It seems that labjack recently updated their website. Some of the "Relevant Documentation" link is now broken showing 404 when attempting to link to the webpage from the Python script.

For example:
Opening and Closing:
        https://labjack.com/support/software/api/ljm/function-reference/opening-and-closing

this link does not work.

**Comment by sjarman28** [comment]
We are working to fix all of the bad links as quickly as possible. Sorry for the inconvenience. In the meantime, if you modify the links in our examples to be under our old website at old3.labjack.com they will all work. For example, see 
https://old3.labjack.com/support/software/api/ljm/function-reference/opening-and-closing

**Comment by sjarman28** [comment]
All of the links that were not working previously should now be getting redirected to our new website. I am going to close this issue now. Please email us at support@labjack.com if you run into any additional link issues.
